CREATE OR REPLACE FUNCTION setDef()
RETURNS TRIGGER AS
$$
BEGIN

	IF NEW.copyright_date < '1973-04-12' THEN
		NEW.copyright_date := '1973-04-12';
		RETURN NEW;
	END IF;
	RETURN NEW;
END;
$$
LANGUAGE plpgsql;



CREATE TRIGGER ALBUM_DATE
BEFORE INSERT OR UPDATE
OF copyright_date
ON ALBUM
FOR EACH ROW
EXECUTE PROCEDURE setDef();